/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CierreRouteImport } from './routes/cierre'
import { Route as NuevoRouteImport } from './routes/nuevo'
import { Route as ComprobanteIdRouteImport } from './routes/comprobante.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CierreRoute = CierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoRoute = NuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprobanteIdRoute = ComprobanteIdRouteImport.update({
  id: '/comprobante/$id',
  path: '/comprobante/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cierre': typeof CierreRoute
  '/nuevo': typeof NuevoRoute
  '/comprobante/$id': typeof ComprobanteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cierre': typeof CierreRoute
  '/nuevo': typeof NuevoRoute
  '/comprobante/$id': typeof ComprobanteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cierre': typeof CierreRoute
  '/nuevo': typeof NuevoRoute
  '/comprobante/$id': typeof ComprobanteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cierre' | '/nuevo' | '/comprobante/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cierre' | '/nuevo' | '/comprobante/$id'
  id: '__root__' | '/' | '/cierre' | '/nuevo' | '/comprobante/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CierreRoute: typeof CierreRoute
  NuevoRoute: typeof NuevoRoute
  ComprobanteIdRoute: typeof ComprobanteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cierre': {
      id: '/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof CierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo': {
      id: '/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof NuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprobante/$id': {
      id: '/comprobante/$id'
      path: '/comprobante/$id'
      fullPath: '/comprobante/$id'
      preLoaderRoute: typeof ComprobanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CierreRoute: CierreRoute,
  NuevoRoute: NuevoRoute,
  ComprobanteIdRoute: ComprobanteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
